[package]
name = "oblivion-terminal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "oblivion-terminal"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
portable-pty = "0.8"
tempfile = "3"

anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
