[package]
name = "oblivion-compositor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true
once_cell.workspace = true
parking_lot.workspace = true

image = "0.25"
rustix = { version = "0.38", features = ["fs"] }
calloop = "0.12"

[features]
default = []
udev = []

[[bin]]
name = "oblivion-compositor"
path = "src/main.rs"